### ISSUE TITLE
Receiving mixed response on POST to /transmissions

### ISSUE THREAD

**Issue by bdeanindy** [SparkPost/python-sparkpost#20] opened 2015-04-26 16:58 UTC
Using the Python SDK, a POST to /transmissions with the BODY.recipients set to an array of strings, shown in example below, returns a mixed 200 response.

```
recipients = ['user@domain.com', 'anotheruser@anotherdomain.com']
```

Response:

```
{u'total_accepted_recipients': 1, u'id': u'30010207866232273', u'rcpt_to_errors': [{u'message': u'invalid data format/type', u'code': u'1300', u'description': u'address  is not JSON'}], u'total_rejected_recipients': 1}
```

The example code shows this as a valid use case:
https://github.com/SparkPost/python-sparkpost/blob/master/examples/transmissions/send_transmission.py#L7

Need to research if this is a valid bug (and resolve) or user error.

**Comment by richleland** [comment] 2015-08-23 01:04
@bdeanindy I just tried this:

```python
from sparkpost import SparkPost

sp = SparkPost()

response = sp.transmission.send(
    recipients=[
        'user@domain.com',
        'anotheruser@anotherdomain.com'
    ],
    html='<p>Hello world {{name}}</p>',
    text='Hello world {{name}}',
    from_email='test@sparkpostbox.com',
    subject='Example Script',
    description='contrived example',
    custom_headers={
        'X-CUSTOM-HEADER': 'foo bar'
    },
    campaign='sdk example',
    metadata={
        'key': 'value',
        'arbitrary': 'values'
    },
    substitution_data={
        'name': 'Example User'
    },
    reply_to='no-reply@sparkpostmail.com'
)

print response
```

With the following results:

```
{u'total_accepted_recipients': 2, u'id': u'48109407176632574', u'total_rejected_recipients': 0}
```

Do you still have the full script that you ran? Otherwise we'll have to close this as I can't reproduce.

**Comment by richleland** [comment] 2015-08-25 02:53
Please re-open or create a new issue if this resurfaces.

**Closed by richleland** 2015-08-25 02:53 UTC
Labels: docs, help wanted, question
